name: iamrich
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
#  Flutter's children
  #  Identation level: two spaces.
  uses-material-design: true
  assets:
#  It is not necessary to use '- images/diamond.png'.
#  Setting the path as '- images/' will add everything inside this folder.
    - images/
